#!/bin/bash
echo "gcc -Wall -Wshadow -g answer02.c && ./a.out" 
gcc -Wall -Wshadow -std=c99 -g answer02.c && ./a.out 
valgrind --tool=memcheck --leak-check=full --verbose --log-file=memcheck.log --track-origins=yes ./a.out
